# Site settings
title: >
  { jdsteinbach }
email: jdsteinbach@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end architect. Speaker & writer.<br/>Sass, CSS animation, RWD &amp; WP.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jdsteinbach.com" # the base hostname & protocol for your site
permalink: /:categories/:title
twitter_username: jdsteinbach
github_username:  jdsteinbach
author_name: James Steinbach
category_suffix: "Category Archive"
profile_pic: "/images/headshot.png"

paginate: 8
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-redirect-from
